version: '3'

services:
    bitrix-cli-install:
        image: bitrix-cli-install
        build: .
        environment:
            BITRIX_DIR: /tmp/bitrix-cli-install
            XDEBUG_CONFIG: $XDEBUG_CONFIG
            PHP_IDE_CONFIG: $PHP_IDE_CONFIG
            HOST_MACHINE: $HOST_MACHINE
        volumes:
            - .:/var/www
            - ${BITRIX_CLI_INSTALL_TARGET:-/tmp/bitrix-cli-install}:/tmp/bitrix-cli-install
        network_mode: host

    mysql:
        image: mysql:5.6
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=${BITRIX_DB_PASSWORD} --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10
        environment:
            MYSQL_DATABASE: ${BITRIX_DB_NAME}
            MYSQL_USER: ${BITRIX_DB_LOGIN}
            MYSQL_PASSWORD: ${BITRIX_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${BITRIX_DB_PASSWORD}
        command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--skip-character-set-client-handshake', '--sql-mode=', '--bind-address=0.0.0.0']

        volumes:
            - /etc/localtime:/etc/localtime/:ro
        network_mode: host
        ports:
            - 3306:3306